/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package application;

import entities.Produto;
import mode.dao.DaoFactory;
import mode.dao.ProdutoDao;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.SwingConstants;
import model.excepion.leitorProduto;

/**
 *
 * @author geniv
 */
public class TelaPrincipal extends javax.swing.JFrame {

    ArrayList<Produto> PRODUTOS;
    String SalvarProdutos = "";

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        criaProdutos();
 setSize(1280,780);
       

    }

    public void criaProdutos() {
        leitorProduto f = new leitorProduto();
        try {
            PRODUTOS = f.lerProdutos("D:\\produtos.txt");
            
            criaBotoes(PRODUTOS);
            
           
            
        } catch (IOException ex) {
            Logger.getLogger(TelaSecundaria.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    public void criaBotoes(ArrayList<Produto> produtos) {
        Principal.removeAll();

        try {

            int cont = 1;
            int altura = 170;
            int largura = 300;
            int x = 155;
            int y = 189;
            int contador = 1;
            int aux = 2;
            // JButton button = null;
            for (Produto produto : produtos) {
            
                		 
                		 
                		 
                		 
                		 
                		 
                		 
                		 
                final JButton button = new JButton(produto.getNome());
                // final JButton button = new JButton(produto.nome);// modificar

                button.setFont(new Font("Tahoma", Font.BOLD, 20));
                button.setHorizontalAlignment(SwingConstants.CENTER);
                button.setHorizontalTextPosition(SwingConstants.CENTER);
                button.setVerticalAlignment(SwingConstants.CENTER);
                button.setVerticalTextPosition(SwingConstants.CENTER);
               

                // valores.setNumero(3);
                button.addActionListener(new ActionListener() {

                    @Override

                    public void actionPerformed(java.awt.event.ActionEvent e) {
                        // if (valor.contains(produto.valorDaQuetinha.get(0))) {

                    TelaSecundaria dialog = new TelaSecundaria(new javax.swing.JFrame(), true,button.getText());
                        dialog.setVisible(true);
                        // }

                    }
                });

                if (Principal.getSize().getWidth() > (largura + contador) + (contador * 8)) {

                    button.setBounds(x, y, largura, altura);
                    Principal.add(button);
                    x = x + largura + 8;
                    contador++;
                    this.repaint();

                } else {
                    if (Principal.getSize().getHeight() > (altura * aux) + aux * 2) {
                        contador = 2;
                        x = 15;
                        y = y + altura + 5;

                        button.setBounds(x, y, largura, altura);

                        Principal.add(button);
                        x = x + largura + 8;
                        aux++;
                        this.repaint();

                    }
                }

                Principal.setAlignmentX(CENTER_ALIGNMENT);
            }

        } catch (Exception e) {
            e.printStackTrace();

        }
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Principal = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(720, 576));

        javax.swing.GroupLayout PrincipalLayout = new javax.swing.GroupLayout(Principal);
        Principal.setLayout(PrincipalLayout);
        PrincipalLayout.setHorizontalGroup(
            PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 515, Short.MAX_VALUE)
        );
        PrincipalLayout.setVerticalGroup(
            PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 433, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Principal, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Principal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Principal;
    // End of variables declaration//GEN-END:variables
}
